[package]
name = "sky"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sky-ui = { workspace = true }

floem = { git = "https://github.com/SerialForker/floem.git", rev = "d87a6a1b38ff7cd90628352efa35ff7b29daaa88" }

paste = { version = "1.0.14" }
reqwest = { version = "0.12.4", features = ["blocking"] }
thiserror = { workspace = true }
url = "2.5.0"
